{{- range $appName, $appConfig := .Values.apps }}
{{- if $appConfig.enabled }}
{{- if $appConfig.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ $.Values.tenantId }}-{{ $appName }}"
  labels:
    app.kubernetes.io/name: "{{ $.Chart.Name }}-{{ $appName }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ $.Values.awsAccountId }}:role/{{ $appName }}-role-{{ $.Values.tenantId }}"
{{- end }}
{{- end }}
{{- end }}
