apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full-permissions-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argoworkflows-sa
  namespace: argo-workflows
  annotations:
    eks.amazonaws.com/role-arn: ${argo_workflows_irsa}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-permissions-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-permissions-cluster-role
subjects:
  - kind: ServiceAccount
    name: argoworkflows-sa
    namespace: argo-workflows
---
# TODO: Configure s3 artifact output
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  dependsOn:
    - name: aws-load-balancer-controller
  releaseName: argo-workflows
  targetNamespace: argo-workflows
  storageNamespace: argo-workflows
  interval: 1m0s
  chart:
    spec:
      chart: argo-workflows
      version: 0.40.11
      sourceRef:
        kind: HelmRepository
        name: argo
  values:
    useStaticCredentials: false
    artifactRepository:
      s3:
        bucket: ${argo_workflows_bucket_name}
        region: ${aws_region}
        endpoint: s3.amazonaws.com
    workflow:
      serviceAccount:
        create: true
        name: "argo-workflow"
        annotations:
          eks.amazonaws.com/role-arn: ${argo_workflows_irsa}
      rbac:
        create: true
    controller:
      workflowNamespaces: # Give permission to other namespaces, to use Karpenter
        - argo-workflows
    server:
      serviceType: LoadBalancer
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      serviceAccount:
        annotations: 
          eks.amazonaws.com/role-arn: ${argo_workflows_irsa}
      extraArgs:
      - --auth-mode=server # This is for demonstration purposes only
  install: {}

  # https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml