apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/production
  prune: true
  validation: client