apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infrastructure/base/sources
  prune: true
  #validation: client
  postBuild:
  substituteFrom:
    - kind: ConfigMap
      name: saas-infra-outputs
      # Use this ConfigMap if it exists, but proceed if it doesn't.
      optional: false