apiVersion: v1
kind: Namespace
metadata:
  name: {TENANT_ID}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {TENANT_ID}-premium
  namespace: flux-system
spec:
  releaseName: {TENANT_ID}-premium
  targetNamespace: {TENANT_ID}
  storageNamespace: {TENANT_ID}
  interval: 1m0s
  chart:
    spec:
      chart: helm-tenant-chart
      version: "{RELEASE_VERSION}.x"
      sourceRef:
        kind: HelmRepository
        name: helm-tenant-chart
  values:
    tenantId: {TENANT_ID}
    apps:
      producer:
        enabled: true # Silo deployment -- premium tier has a dedicated deployment for each tenant
        ingress:
          enabled: true
        image:
          tag: "0.1" # {"$imagepolicy": "flux-system:producer-image-policy:tag"}
      consumer:
        enabled: true # Silo deployment -- premium tier has a dedicated deployment for each tenant
        ingress:
          enabled: true
        image:
          tag: "0.1" # {"$imagepolicy": "flux-system:consumer-image-policy:tag"}
